[package]
name = "due-date-calculator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
test-case = "3.1.0"
thiserror = "1.0.40"
chrono = "0.4.26"
lazy_static = "1.4.0"
